### ISSUE TITLE
[FEATURE] Foundry V12 Support

### ISSUE THREAD

**Issue by BoltsJ** [Eranziel/foundryvtt-lancer#650]
Main list of things for v12 support

[V12 Breaking Changes](https://github.com/orgs/foundryvtt/projects/42/views/9)
 
- [x] Remove deprecations from v10 - foundryvtt/foundryvtt#10164
- [x] Use TypeDataModel instead of DataModel for document data - [System Data Model Documentation](https://foundryvtt.com/article/system-data-models/)
  - [ ] (optional) Move type-specific portions of prepareBaseData and prepareDerivedData to the data models
  - [ ] (Optional) Cleanly handle subtypes not provided by the system (`base` or module provided subtypes for example)
- [x] (Optional) Remove template.json and define document types in system.json - https://github.com/foundryvtt/foundryvtt/issues/10444 [Manifest defined types](https://foundryvtt.com/article/module-sub-types/)
- [x] Fix Measured templates - Canvas changes, foundryvtt/foundryvtt#10088
  - [x] Update Measured Templates to use grid based shapes foundryvtt/foundryvtt#10476
- [x] Update manifest grid configuration - foundryvtt/foundryvtt#9999
- [x] Remove square diagonal system setting
- [ ] (Optional) Migrate applications to app v2, possibly using a Svelte backend for rendering contents - foundryvtt/foundryvtt#5441
- [x] Ensure node version in workflows and guides is bumped to at least 18
- [ ]  (Optional) Custom data model for Combat, Combatant, ChatMessage and ActiveEffect - foundryvtt/foundryvtt#10185
- [x] Investigate whether the dynamic token ring system can be leveraged to create hex borders for tokens – It cannot
- [ ] (Optional) Add \@\Embed support for Documents, e.g. creating statblocks for npcs in journals. - foundryvtt/foundryvtt#10262
- [x] Use data fields for settings. See core settings for examples
- [x] Round borders on gridless
- [ ] Use max and min properties of ArrayField in favor of the custom BoundedArrayField

Bugs 🐛 :
- [x] Pilot imports don't properly copy the permission config from the pilot to the imported mechs and deployables.

**Comment by Eranziel** [comment]
Thanks so much for this list, very helpful! All in all, doesn't look too bad.

**Comment by BoltsJ** [comment]
It may or may not be a complete list. This is just based on memory (I have ADHD, so) and reading the breaking changes list.

**Comment by C-S-McFarland** [comment]
Using V12 today, I imported an ACE NPC from the pre-built NPC compendium, and it seems that by default, any chargeable systems are uncharged. I think these should be charged by default.

**Comment by BoltsJ** [comment]
> Using V12 today, I imported an ACE NPC from the pre-built NPC compendium, and it seems that by default, any chargeable systems are uncharged. I think these should be charged by default.

That's a change that should just go straight to main, tbh.

**Comment by Eranziel** [comment]
Closed by #725. Going to spin out separate issues for the remaining tasks.
